source "https://rubygems.org"

gem "jekyll"
gem "minima"
# Add other gems you need for your site

# If you want to include GitHub Pages gem, uncomment the following line:
# gem "github-pages", group:
